#+TITLE: Vida artificial

Aritificial Life Langton 1987

Estudiar sistemas artificales con caracteristicas similares a los sistemas vivos

Bottom up.
- Definir reglas para el sistema que que exhiba emergencia

Game of life Conway 1970
- Celda muerta con tres vecinos vivos nace
- Celda con uno o menos vecinos muere por soledad
- Celda con cuatro o más vecinos muere por sobrepoblación
Turing Completo

Von Neumann: Debe existir una máquina de Turing capaza de simular procesos
biológicos

Loop de Langton 1984
Autómata celular autoreplicable con 8 reglas

Biological automata (wetware)

GTYPE PTYPE

Genetic algorithms John Holland 1975

Evolving creatures Karl Sims 1994

* Autómatas celulares

** Historia
Turing decisión

Gödel completidud

Von Neuman autómatas celulares

? retículas

Langton

Wolfram dinámica de autómatas

** Definición

$\{0, 1\}$ estados.

$a_i(t)$ es el estado de la celda $i$ en el instante $t$.

$a_i(t+1) = F(a_{i-a}, a_i(t), a_{i+1}(t)$ función de transición.

Hay $2^3$ entradas (pues hay tres bits). Así que hay $2^{2^3} = 256$ posibles
funciones $F$. Se pueden indentificar del 0 al 255.

- Regla 110: Turing completa

** Clasificaciónde Wolfram
- Punto fijo
- Estructuras periódicas
- Patrones caóticos y estructuras fractales
- Estructuras complejas

Conjetura de borde del caos (Langton): se pueden ordenar las reglas en base a su
desorden. Las reglas complejas están en la frontera entre orden y desorden.

** Juego de la vida

Autómatas bidimencionales Turing completo.

Retícula de $m\times n$ con vecindades de Moore.

Estructuras estables y dinámicas

*** Turing completez


- Pulsos: gliders
- Cables: trayectorias de gliders
- Reloj: pistolas y eaters
- Compuertas: demás estrucutras estables


* Loop de Langton

- 2: coraza
  - 1: núcleo
    - 7: destruye coraza
      - 6: crea coraza
        - 4: copia
* Modelos

Predictivo y descriptivo

Ciclo de modelación, simulación y validación

** Regeneración de bosques
Iwaza: surmiento de franjas de árboles muertos en boques de abetos
¿Terreno, viento, recursos?

Modelación con autómatas celulares. $S_t(i, j)$ la altura del árbol $i, j$ en el
tiempo $t$. En cada tiempo crece hasta que alcanza un umbral de altura, y luego
muere.

Este umbral depende del promedio de altura de la vecindad. Esta vecindad depende
de la dirección del viento.

* Fractales

Mandelbrot: la naturaleza no es regular.

Un fractal es un objeto geométrico cuya estrucutra se repite a diferentes
escalas.

- Demasiado irregluar para ser descrito de otra manera
- Es autosimilar
- Se puede definir recursivamente

** Box counting

En qué dimensión está un objeto

** Ejemplos

Atractor de Lorenz, conjuntos de Julia, autómatas celulares, construcciones
geométricas.
